const sprite = {
    reference: document.querySelectorAll(".perso_anne > img")[0],
    frameX: -128,
    idle: {
        placement: -20,
        nombreDeFrames: 4,
    },
    marcherADroite: {
        placement: -789,
        nombreDeFrames: 8,
    },
    marcherAGauche: {
        placement: -916,
        nombreDeFrames: 8,
    },
    directionDesImages: "left",
};

const elementsJeu = {
    ///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    //MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM PNJ MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    // MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    pnj: {
        chien01: {
            apparitionX: 330,
            apparitionY: 28,
            width: 60,
            id: "chien01",
            class: "pnj_chien",
            url: "images/sprites/chien02.png",
            droite: false,
        },
        chien02: {
            apparitionX: 3330,
            apparitionY: 28,
            width: 60,
            id: "chien02",
            class: "pnj_chien",
            url: "images/sprites/chien03.png",
            droite: true,
        },
        sorcier: {
            apparitionX: 6130,
            apparitionY: 28,
            width: 60,
            id: "sorcier",
            class: "pnj_sorcier",
            url: "images/sprites/whitewitch.png",
            droite: true,
        },
        chien03: {
            apparitionX: 7710,
            apparitionY: 320,
            width: 60,
            id: "chien03",
            class: "pnj_chien",
            url: "images/sprites/chien04.png",
            droite: true,
        },
        chien04: {
            apparitionX: 8200,
            apparitionY: 28,
            width: 60,
            id: "chien04",
            class: "pnj_chien",
            url: "images/sprites/chien07.png",
            droite: true,
        },
    },
    ///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    // ICI LES PANNEAUX MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM//
    // MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    panneaux: {
        limitegauche: {
            apparitionX: 120,
            apparitionY: 40,
            width: 140,
            id: "limitegauche",
            class: "panneaux",
            url: "images/panneaux/panneaulimite.png",
            droite: false,
        },
        sodexo: {
            apparitionX: 1400,
            apparitionY: 40,
            width: 120,
            id: "sodexo",
            class: "panneaux",
            url: "images/panneaux/sodexo.png",
            droite: true,
        },
        datawords: {
            apparitionX: 3600,
            apparitionY: 40,
            width: 120,
            id: "datawords",
            class: "panneaux",
            url: "images/panneaux/datawords.png",
            droite: true,
        },
        ifocop: {
            apparitionX: 9800,
            apparitionY: 40,
            width: 120,
            id: "ifocop",
            class: "panneaux",
            url: "images/panneaux/ifocop.png",
            droite: true,
        },
        fin: {
            apparitionX: 8600,
            apparitionY: 40,
            id: "fin",
            class: "panneaux",
            url: "images/panneaux/fin.png",
            droite: true,
        },
        fin2: {
            apparitionX: 8700,
            apparitionY: 40,
            id: "fin2",
            class: "panneaux",
            url: "images/panneaux/fin.png",
            droite: true,
        },
        rocher: {
            apparitionX: 9200,
            apparitionY: 36,
            id: "rocher",
            class: "panneaux",
            url: "images/panneaux/rocher.png",
            droite: true,
        },
    },
    ///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    //MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM PLATEFORMES MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    // MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    plateformes: {
        plat0: {
            apparitionX: 1700,
            apparitionY: 140,
            width: 290,
            url: "images/platforms/city_verylong_clair.png",
            id: "plat0",
            visible: false,
            droite: true,
            class: "plateforme plat-long",
        },
        plat1: {
            apparitionX: 2200,
            apparitionY: 110,
            width: 100,
            url: "images/platforms/city_small_clair.png",
            id: "plat1",
            visible: false,
            droite: true,
            class: "plateforme plat-small",
        },
        plat2: {
            apparitionX: 2500,
            apparitionY: 200,
            width: 190,
            url: "images/platforms/city_long_clair.png",
            id: "plat2",
            visible: false,
            droite: true,
            class: "plateforme plat-med",
        },
        plat2a: {
            apparitionX: 2800,
            apparitionY: 100,
            width: 290,
            url: "images/platforms/city_verylong_clair.png",
            id: "plat2a",
            visible: false,
            droite: true,
            class: "plateforme plat-long",
        },
        plat3: {
            apparitionX: 3920,
            apparitionY: 110,
            width: 100,
            url: "images/platforms/city_small_clair.png",
            id: "plat3",
            visible: false,
            droite: true,
            class: "plateforme plat-small",
        },
        plat4: {
            apparitionX: 4200,
            apparitionY: 110,
            width: 100,
            url: "images/platforms/city_small_clair.png",
            id: "plat4",
            visible: false,
            droite: true,
            class: "plateforme plat-small",
        },
        plat5: {
            apparitionX: 4600,
            apparitionY: 140,
            width: 290,
            url: "images/platforms/city_verylong_clair.png",
            id: "plat5",
            visible: false,
            droite: true,
            class: "plateforme plat-long",
        },
        plat6: {
            apparitionX: 5000,
            apparitionY: 300,
            width: 190,
            url: "images/platforms/city_long_clair.png",
            id: "plat6",
            visible: false,
            droite: true,
            class: "plateforme plat-med",
        },
        plat7: {
            apparitionX: 6400,
            apparitionY: 100,
            width: 190,
            url: "images/platforms/forest_simple.png",
            id: "plat7",
            visible: false,
            droite: true,
            class: "plateforme forest-med",
        },
        plat8: {
            apparitionX: 6700,
            apparitionY: 300,
            width: 190,
            url: "images/platforms/forest_tree.png",
            id: "plat8",
            visible: false,
            droite: true,
            class: "plateforme forest-med-tree",
        },
        plat9: {
            apparitionX: 7000,
            apparitionY: 100,
            width: 290,
            url: "images/platforms/forest_simple_long.png",
            id: "plat9",
            visible: false,
            droite: true,
            class: "plateforme forest-long",
        },
        plat10: {
            apparitionX: 7300,
            apparitionY: 150,
            width: 100,
            url: "images/platforms/forest_small.png",
            id: "plat10",
            visible: false,
            droite: true,
            class: "plateforme forest-small",
        },
        plat11: {
            apparitionX: 7600,
            apparitionY: 300,
            width: 190,
            url: "images/platforms/forest_tree.png",
            id: "plat11",
            visible: false,
            droite: true,
            class: "plateforme forest-med-tree",
        },
        plat12: {
            apparitionX: 7900,
            apparitionY: 130,
            width: 100,
            url: "images/platforms/forest_small.png",
            id: "plat12",
            visible: false,
            droite: true,
            class: "plateforme forest-small",
        },
        plat13: {
            apparitionX: 71000,
            apparitionY: 130,
            width: 100,
            url: "images/platforms/forest_small.png",
            id: "plat13",
            visible: false,
            droite: true,
            class: "plateforme forest-small",
        },
    },
    ///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    //MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM BONUS MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    // MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM //
    bonus: {
        explorateur: {
            apparitionX: 145,
            apparitionY: 220,
            url: "images/icones/bonus_explo.png",
            id: "explorateur",
            class: "bonus",
            visible: false,
            droite: false,
            titre: `Bonus Explorateur`,
        },
        diplome1: {
            apparitionX: 1000,
            apparitionY: 28,
            url: "images/icones/diplome_1.png",
            id: "bonus1",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Master d'anglais`,
        },
        diplome2: {
            apparitionX: 1400,
            apparitionY: 28,
            url: "images/icones/diplome_2.png",
            id: "bonus2",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Master d'allemand`,
        },
        defendre: {
            apparitionX: 1800,
            apparitionY: 300,
            url: "images/icones/defendre.png",
            id: "defendre",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Défendre ses idées`,
        },
        lourd: {
            apparitionX: 2000,
            apparitionY: 380,
            url: "images/icones/lourd.png",
            id: "lourd",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Forger le caractère`,
        },
        stratego: {
            apparitionX: 2450,
            apparitionY: 350,
            url: "images/icones/strategie.png",
            id: "stratego",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Planning stratégique`,
        },
        marketing: {
            apparitionX: 2200,
            apparitionY: 310,
            url: "images/icones/marketing.png",
            id: "marketing",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Marketing`,
        },
        entraide: {
            apparitionX: 2400,
            apparitionY: 30,
            url: "images/icones/entraide.png",
            id: "entraide",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Esprit d'entraide`,
        },
        planning: {
            apparitionX: 2800,
            apparitionY: 260,
            url: "images/icones/planning.png",
            id: "planning",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Gérer les plannings`,
        },
        multilingue: {
            apparitionX: 3050,
            apparitionY: 350,
            url: "images/icones/multilingue.png",
            id: "multilingue",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Equipes multilingues`,
        },
        vba: {
            apparitionX: 3050,
            apparitionY: 50,
            url: "images/icones/vba.png",
            id: "vba",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Programmation VBA`,
        },
        diplome3: {
            apparitionX: 4030,
            apparitionY: 300,
            url: "images/icones/diplome_3.png",
            id: "bonus3",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Gestion de projet`,
        },
        estomac: {
            apparitionX: 4200,
            apparitionY: 300,
            url: "images/icones/estomac.png",
            id: "estomac",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Estomac bien accroché`,
        },
        seo: {
            apparitionX: 4400,
            apparitionY: 30,
            url: "images/icones/seo.png",
            id: "seo",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `SEO`,
        },
        budget: {
            apparitionX: 4510,
            apparitionY: 320,
            url: "images/icones/budget.png",
            id: "budget",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Gestion des budgets`,
        },
        commercial: {
            apparitionX: 5000,
            apparitionY: 350,
            url: "images/icones/commercial.png",
            id: "estomac",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Présenter aux clients`,
        },
        coeur: {
            apparitionX: 4700,
            apparitionY: 380,
            url: "images/icones/coeur.png",
            id: "coeur",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Résister au stress`,
        },
        plante: {
            apparitionX: 5080,
            apparitionY: 30,
            url: "images/icones/plante.png",
            id: "plante",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Main verte`,
        },
        equipe: {
            apparitionX: 5300,
            apparitionY: 250,
            url: "images/icones/partage.png",
            id: "equipe",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Esprit d'équipe`,
        },

        //MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MONDE FORET MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM//  
        htmlcss: {
            apparitionX: 6500,
            apparitionY: 50,
            url: "images/icones/html.png",
            id: "htmlcss",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `HTML / CSS`,
        },
        javascript: {
            apparitionX: 6600,
            apparitionY: 300,
            url: "images/icones/javascript.png",
            id: "javascript",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Vanilla JS`,
        },
        jquery: {
            apparitionX: 6800,
            apparitionY: 350,
            url: "images/icones/jquery.png",
            id: "jquery",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `jquery`,
        },
        mongo: {
            apparitionX: 7000,
            apparitionY: 300,
            url: "images/icones/mongo.png",
            id: "mongo",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `MongoDB`,
        },
        meteor: {
            apparitionX: 7300,
            apparitionY: 320,
            url: "images/icones/meteor.png",
            id: "meteor",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `meteor`,
        },
        cafe: {
            apparitionX: 7400,
            apparitionY: 50,
            url: "images/icones/cafe.png",
            id: "cafe",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Résistance au café`,
        },
        expressjs: {
            apparitionX: 7500,
            apparitionY: 350,
            url: "images/icones/express.png",
            id: "expressjs",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `expressJS`,
        },
        node: {
            apparitionX: 7810,
            apparitionY: 360,
            url: "images/icones/node.png",
            id: "node",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Node.JS`,
        },
        websockets: {
            apparitionX: 7900,
            apparitionY: 170,
            url: "images/icones/websockets.png",
            id: "websockets",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Websockets`,
        },
        angular: {
            apparitionX: 8000,
            apparitionY: 350,
            url: "images/icones/angular.png",
            id: "angular",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Angular JS`,
        },
        git: {
            apparitionX: 8100,
            apparitionY: 150,
            url: "images/icones/git.png",
            id: "git",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `GIT de ouf`,
        },
        poissonclown: {
            apparitionX: 8400,
            apparitionY: 50,
            url: "images/icones/humour.png",
            id: "poissonclown",
            class: "bonus",
            visible: false,
            droite: true,
            titre: `Sens de l'humour`,
        },
        diplomeifocop: {
            apparitionX: 9200,
            apparitionY: 150,
            url: "images/icones/diplomeifocop.png",
            id: "diplomeifocop",
            class: "bonus",
            visible: false,
            droite: true,
            titre: ` `,
        },
    },
};